### ISSUE TITLE
scServer.exchange vs scServer.global

### ISSUE THREAD

**Issue by devhyunjae** [happilymarrieddad/sc-horizontal#1]
Thanks for the awesome sample app with scaling.

Can i ask about the difference between `exchange and global object?`

In the sc doc it explains about exchange
http://socketcluster.io/#!/docs/api-exchange
but there is no comments about global object

**Comment by happilymarrieddad** [comment]
The global object was the way you did it before the exchange object was available. Please use exchange now. Thanks!
